name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"  # Add caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]  # Install from setup.py

      - name: Run linting (flake8)
        run: flake8 src/ --count --max-line-length=88 --statistics

      - name: Run type checking (mypy)
        run: mypy src/

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=src --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
